//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakilaTopicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public int customer_id { get; set; }
        public byte staff_id { get; set; }
        public Nullable<int> rental_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime payment_date { get; set; }
        public System.DateTime last_update { get; set; }
    
        public virtual rental rental { get; set; }
        public virtual staff staff { get; set; }
    }
}
