//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakilaTopicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class rental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rental()
        {
            this.payment = new HashSet<payment>();
        }
    
        public int rental_id { get; set; }
        public System.DateTime rental_date { get; set; }
        public int inventory_id { get; set; }
        public int customer_id { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public byte staff_id { get; set; }
        public System.DateTime last_update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
        public virtual staff staff { get; set; }
    }
}
